output_dir: output

samples: &samples
  path: '/s3/giuliac/EJFullRun3/TrainingOutputs/20260221_EnhanceJet/epoch=008-val_jet_loss=0.02734__test_9574840.pp_output_val.h5'
  label: 'enhancejet'
  df_name: tracks

style: &style
  ylabel: ""
  xlabel: ""
  figsize: !!python/tuple [10, 5]
  use_atlas_tag: True
  atlas_first_tag: "Simulation Internal"
  atlas_second_tag: "enhancejet, $\\sqrt{{s}}=13.6$ TeV"
  y_scale: 1.0
  fontsize: 15
  label_fontsize: 15
  dpi: 300

plots:
  vertex:
    class: plotter.plot_classes.vertex_plot_9labels.VertexPlotBase
    samples: *samples
    file_name: ../plots/EJsFullRun3/WeightComparison/enhancejet/VImatrices/1jet16-VImat.pdf
    jet_num: 16
    pEJ_min: 0.98
    pEJ_max: 1.0
    is_Disp: 1 # 0 for truth prompt jet, 1 for truth emerging jet
    zoom: False
    style:
      <<: *style
      figsize: !!python/tuple [10,5]
      xlabel: "$n_{track}$"
      ylabel: "$n_{track}$"
      show_entries: False
      show_percentages: False
      text_color_threshold: 0.6
      colormap: gray
      cbar_label: ""