output_dir: output

samples: &samples
  path: '/s3/giuliac/EJFullRun3/TrainingOutputs/20260221_EnhanceTrackOrigin/epoch=009-val_jet_loss=0.02562__test_9574840.pp_output_val.h5'
  label: 'enhancetrackorigin'

style: &style
  ylabel: ""
  xlabel: ""
  figsize: !!python/tuple [7, 5]
  logy: True
  use_atlas_tag: True
  #atlas_brand: ""
  #atlas_first_tag: "Simulation Internal"
  atlas_second_tag: "enhancetrackorigin, $\\sqrt{{s}}=13.6$ TeV"
  y_scale: 1.0
  fontsize: 15
  label_fontsize: 15
  dpi: 300

plots:
  discrim:
    class: plotter.plot_classes.discrim_plot.DiscrimPlotBase
    samples: *samples
    low: 0.00
    high: 1.00
    dx: 0.01
    file_name: ../plots/EJsFullRun3/WeightComparison/enhancetrackorigin/discrim.pdf
    style:
      <<: *style
      n_ratio_panels: 1
      ylabel: "Normalized number of jets"
      xlabel: "GN3ej Discriminant"
      y_scale: 1.3