output_dir: output

samples: &samples
  GN3ej:
    path: '/home/private/EmergingJetTagger/salt/salt/logs/20251113_FirstFold0Training/ckpts/epoch=010-val_loss=0.02675__test_9574840.pp_output_val.h5'
    label: "GN3ej-combined-extLabels-fold0-classdict"
    reference: True
    df_name: jets

style: &style
  ylabel: ""
  xlabel: ""
  figsize: !!python/tuple [7, 6]
  use_atlas_tag: True
  #atlas_brand: ""
  #atlas_first_tag: "Simulation Internal"
  atlas_second_tag: "$\\sqrt{{s}}=13.6$ TeV"
  y_scale: 1.0
  label_fontsize: 15
  fontsize: 15
  atlas_fontsize: 15

plots:
  roc:
    class: plotter.plot_classes.roc_plot.RocPlotBase
    samples: *samples
    file_name: ../plots/EJsFullRun3/roc.pdf
    target_label: isDisplaced
    tagger_output: GN3ej-fold0
    range: !!python/tuple [0.80, 1, 100]
    leg_inside: True
    leg_fontsize: 12
    reference_label: "$Z'$"
    show_cuts: True
    cut_values: [0.98]  # or None
    #cut_values: [0.90,0.98,0.99]  # or None
    style:
      <<: *style
      n_ratio_panels: 1
      ylabel: "QCD rejection"
      xlabel: "EJ tagging efficiency"
      y_scale: 1.5