output_dir: output

samples: &samples
  path: '/home/private/EmergingJetTagger/salt/salt/logs/20251113_FirstFold0Training/ckpts/epoch=010-val_loss=0.02675__test_9574840.pp_output_val.h5'
  label: 'GN3ej-combined-extLabels-fold0'
  df_name: tracks

style: &style
  ylabel: ""
  xlabel: ""
  figsize: !!python/tuple [10, 5]
  use_atlas_tag: True
  atlas_first_tag: "Simulation Internal"
  atlas_second_tag: "$Z'$ portal, $\\sqrt{{s}}=13.6$ TeV"
  y_scale: 1.0
  fontsize: 15
  label_fontsize: 15
  dpi: 300

plots:
  vertex:
    class: plotter.plot_classes.vertex_plot_9labels.VertexPlotBase
    samples: *samples
    file_name: ../plots/EJsFullRun3/jet20-VImat.pdf
    jet_num: 1507
    zoom: True
    style:
      <<: *style
      figsize: !!python/tuple [10,5]
      xlabel: "$n_{track}$"
      ylabel: "$n_{track}$"
      show_entries: False
      show_percentages: False
      text_color_threshold: 0.6
      colormap: gray
      cbar_label: ""